# Generated by Django 4.2.23 on 2025-06-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botrun',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking async execution', max_length=255),
        ),
        migrations.AddField(
            model_name='botrun',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes or comments about this run'),
        ),
        migrations.AddField(
            model_name='botrun',
            name='run_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters passed when starting this run'),
        ),
    ]
