# Generated by Django 4.2.23 on 2025-06-27 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='api_key_public_part',
            field=models.CharField(help_text='Public part of the API key (non-sensitive)', max_length=255),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='encrypted_credentials',
            field=models.BinaryField(help_text='Encrypted private API credentials'),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='exchange',
            field=models.ForeignKey(help_text='Exchange this API key is for', on_delete=django.db.models.deletion.CASCADE, related_name='user_api_keys', to='exchanges.exchange'),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this API key is currently active'),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='name',
            field=models.CharField(help_text='User-friendly name for this API key', max_length=100),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='nonce',
            field=models.BinaryField(help_text='Cryptographic nonce for encryption/decryption'),
        ),
    ]
